ruby '>= 2.6.0'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.3.0'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 2.10'
gem 'middleman-sprockets', '~> 4.1'
gem 'sassc', '~> 2.4'
gem 'rouge', '~> 3.30'
gem 'redcarpet', '~> 3.5'
gem 'nokogiri', '~> 1.13'
gem 'haml', '~> 5.2'
gem 'rack', '~> 2.2'
gem 'addressable', '~> 2.8'
gem 'tzinfo', '~> 1.2', '>= 1.2.10'
gem 'ffi', '1.15.5'
